version: 2.1
jobs:
  build:
    docker:
      # Use this New Image for Starting things up
      - image: fr3akyphantom/droid-runner:latest # DO Not Change
    environment:
      MANIFEST_BRANCH: "android-10.0"
      VERSION: "2.9.1" # Change as necessary
      VENDOR: "xiaomi"
      CODENAME: "rolex" # Mandatory
      FLAVOR: "eng" # Mandatory:: Input "eng" or "userdebug"
      MAINTAINER: "PBRP Team"
      TEST_BUILD: 'true'
      # PB_OFFICIAL: 'true' # REQUIRED-FOR-TEAM:: Uncomment only for Stable Official builds
      # PB_ENGLISH: 'true' # Use if necessary
      # EXTRA_CMD: "" # OPTIONAL COMMANDS:: USE WITHIN DOUBLE-QUOTE
      CHANGELOG: |
        What's been done?
        - Update done for xx
        What's fixed?
        - Fixed yy things
          - Which is actually Changed by ZZ
        And something else
    working_directory: /home/builder/ # This MUST NOT Be Changed
    steps:
      - setup_remote_docker:
          version: 19.03.8
      - run:
          name: "ALL IN REMOTE"
          command: |
            wget -q https://raw.githubusercontent.com/PitchBlackRecoveryProject/vendor_utils/pb/remote_build.sh
            source remote_build.sh

workflows:
  version: 2
  remote_builder:
    jobs:
      - build:
          filters:
            branches:
              only: "android-10.0" # Use Appropriate Branch Name
          context: org-global
